#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_ssm="$(cat "$shome/.ssm-version" 2>/dev/null)"
  jq -n --arg ssm "$ver_ssm" '{ssm: $ssm}'
}

version "$@"
